# Generated by Django 5.1.2 on 2025-02-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='data',
            field=models.URLField(),
        ),
    ]
